DELETE FROM tasks;
DELETE FROM sqlite_sequence WHERE name='tasks';

INSERT INTO tasks (title, html_file, category, level) VALUES
  ('EV3 Step 1: Two Beeps & Name',                  '03_01LegoEV3_I.html',        'ev3',    'basic'),
  ('EV3 - drive a square',                          '03_02LegoEV3_I.html',        'ev3',    'basic'),
  ('EV3 - drive a circle',                          '03_03LegoEV3_I.html',        'ev3',    'basic'),
  ('EV3 - drive a figure 8',                        '03_04LegoEV3_I.html',        'ev3',    'basic'),
  ('EV3 - stop in front of a wall',                 '03_05LegoEV3_I.html',        'ev3',    'basic'),
  ('EV3 - find the door (touch)',                   '03_06LegoEV3_I.html',        'ev3',    'basic'),
  ('EV3 - find the door (touch & gyro)',            '03_07LegoEV3_I.html',        'ev3',    'basic'),
  ('EV3 - drive a square with gyro',                '03_08LegoEV3_I.html',        'ev3',    'basic'),
  ('EV3 - line follower',                           '03_09LegoEV3_I.html',        'ev3',    'basic'),
  ('EV3 - line follower & touch',                   '03_10LegoEV3_I.html',        'ev3',    'basic'),
  ('EV3 - warehouse mission',                       '04_01LegoEV3_I.html',        'ev3',    'advanced'),
  ('EV3 - warehouse mission & person safety',       '04_02LegoEV3_I.html',        'ev3',    'advanced'),
  ('Task 1: Hello World',                           '03_01python_I.html',         'python', 'basic'),
  ('Task 2: Variables & print()',                   '03_02python_I.html',         'python', 'basic'),
  ('Task 3: Chosse an operation',                   '03_03python_I.html',         'python', 'basic'),
  ('Task 4: Factorial with for loop',               '03_04python_I.html',         'python', 'basic'),
  ('Task 5: Numbers 1 to X and their sum',          '03_05python_I.html',         'python', 'basic'),
  ('Task 6: Fibonacci sequence up to X',            '03_06python_I.html',         'python', 'basic'),
  ('Task 7: Find min and max from a list',          '03_07python_I.html',         'python', 'basic'),
  ('Task 8: Check if a year is a leap year',        '03_08python_I.html',         'python', 'basic'),
  ('Task 9: Check if a number is prime',            '03_09python_I.html',         'python', 'basic'),
  ('Task 10: All prime numbers up to a limit',      '03_10python_I.html',         'python', 'basic'),  
  ('Task 11: Lottery – draw 6 numbers from 49',     '03_11python_I.html',         'python', 'basic'),
  ('Task 12: The Collatz sequenc',                  '03_12python_I.html',         'python', 'basic'),
  ('Task 1: Shuffle letters inside words',          '03_13python_I.html',         'python', 'advanced'),
  ('Task 2: Linear function f(x) = y = m·x + t',    '03_14python_I.html',         'python', 'advanced'),
  ('Task 3: The Collatz sequenc',                  '03_15python_I.html',         'python', 'advanced'),
  ('Task 4: The Collatz sequenc',                  '03_16python_I.html',         'python', 'advanced');